### PR TITLE
Check if FMU exists

### PR DESCRIPTION
**Pull request by lochel**
### Purpose

Check if FMU exists before loading it.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/959//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#550

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/961//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#550

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[ASan:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/961/)** The test suite is unstable. :worried:

**Comment by lochel** [comment]
@robbr48 Recently, tlm tests failed again quite frequently. 😒

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/964//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#550

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :blush:

**Pull request closed without merging**
