### PR TITLE
Implement oms_getTLMVariableTypes

### PR DESCRIPTION
**Pull request by robbr48**
### Purpose

API function for getting TLM variable types and descriptions.

### Type of Change

- New feature (non-breaking change which adds functionality)

### Checklist

- I have performed a self-review of my own code

### CODE REVIEW

**Comment by robbr48** [comment]
@adeas31 Is this what you need?

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/857//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#482

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/858//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#482

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :sun_with_face:

**Pull request closed without merging**
