### PR TITLE
Added oms3_deleteConnection API

### PR DESCRIPTION
**Pull request by adeas31**
### Purpose

Allow deleting the connection.

### Type of Change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

### Checklist

- I have performed a self-review of my own code
- I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/761//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#447
  - OpenModelica/OMSimulator-testsuite#107

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/761/)** The test suite is unstable. :disappointed:

**Comment by lochel** [comment]
Thanks! 👍

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/762//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#447
  - OpenModelica/OMSimulator-testsuite#107

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :smile:

**Pull request closed without merging**
