### PR TITLE
Make OMSimulator support integer connections

### PR DESCRIPTION
**Pull request by farkasrebus**
### Related Issues

#415 (partial fix)

### Purpose

Support integer signal connections between FMUs.

### Approach

Before updating signal values, the type is checked and the appropriate get/set functions are called.

### Type of Change

- New feature (non-breaking change which adds functionality)

### Checklist

- I have performed a self-review of my own code

### CODE REVIEW

**Comment by lochel** [comment]
Thanks for your contribution. This approach updates the discrete connections on each communication step, right? That is not really necessary, but also not really an issue at this point. 

Can you please squash the commits? After that I can start the Hudson job to test and push the changes.

**Comment by farkasrebus** [comment]
Yes, the discrete connections are updated each step. 

I have squashed the commits. I'm not sure if it is okay now, since a merge commit was created. (This is my first ever pull request, so the workflow is quite new to me.)

**Comment by adeas31** [comment]
You can combine the commits and force push them.

**Comment by meek1** [comment]
Please consider to implement also Boolean connections.

**Comment by lochel** [comment]
I think we can skip implementing boolean connections for oms2 if there is no use case for them right now. We will support interger/boolean connections in oms3 later this year.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/801//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#466

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/801/)** The test suite is unstable. :worried:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/802//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#466

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :tada:

**Comment by meek1** [comment]
OK, I thought this was for oms3. @lochel, in oms3 we actually need Boolean connections for the SSP workflow demo.

**Pull request closed without merging**
