### PR TITLE
Check for inf and nan

### PR DESCRIPTION
**Pull request by lochel**
### Purpose

Test for finit values when fetching signals from FMUs.

### Type of Change

- Bug fix (non-breaking change which fixes an issue)

### Checklist

- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/422//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#244

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/422//console)** The job failed to compile. :unamused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/423//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#244

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :tada:

**Comment by meek1** [comment]
@lochel what happens if inf/nan values are found during simulation? Warning and replacement of inf/nan in result file?

**Comment by lochel** [comment]
Error message, including the variable name, and abortion of the simulation.

**Comment by lochel** [comment]
All simulation results should be available until the failing step, regardless of whether buffering is used or not. However, this is not tested, because I don't have a FMU that returns nan at any time point.

**Pull request closed without merging**
