### PR TITLE
Added missing getXXX/setXXX oms2 API functions

### PR DESCRIPTION
**Pull request by bernhard-thiele**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being tested. It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#127

**Comment by bernhard-thiele** [comment]
@lochel I mechanically added the missing API function using the existing functions as example. A drawback is that there is a lot of code bloat due to cloned pieces of code. Probably one could extract common parts of the setXXX/getXXX functions and reduce the bloat.

**Comment by lochel** [comment]
Yes, that might be a good idea. But I think for now the changes look fine and can be merged.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being tested. It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#127

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :relaxed:

**Pull request closed without merging**
