### PR TITLE
Introduce flag --zeroNominal

### PR DESCRIPTION
**Pull request by lochel**
### Related Issues

* #1013 

### Description

The new flag will force 1.0 as nominal values for all invalid nominal values. It also changes the error messages slightly.

### CODE REVIEW

**Review by AnHeuermann — APPROVED** [review]
Lgtm

**Review by arun3688 — APPROVED** [review]

**Comment by max-privato** [comment]
This will be activated in OMEdit with --zeroNominal=true ,  guess? (as per the following picture).
If the answer is yes I must wait for tomorrow's nightly build, since today's (dev-246) does not accept this flag.

In the meanwhile, I've tried also to manually set nominal=1 in the original modelica file, and this gave rise to other issues with OM/SSP, that I will report in another ticket, once I've sussessfully tried this flag.

Thanks a lot for your very fast and effective support!

flags

**Comment by lochel** [comment]
The answer is yes, although a bit late ;)

**Comment by max-privato** [comment]
great addition!

I'll use it all the time... up to when Dassault fixes Dymola. Symantec has acknowledged Dymola has a fault and passed my report to the developers (I sent a copy of the mail to @casella ).

**Pull request merged**
