### PR TITLE
Fix setTLMPositionAndOrientation

### PR DESCRIPTION
**Pull request by robbr48**
### Purpose

Fix implementation of oms3_setTLMPositionAndOrientation Lua call.

### Approach

Correct number of arguments check.

### Type of Change

- Bug fix (non-breaking change which fixes an issue)

### Checklist

- I have performed a self-review of my own code
- I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/905//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#525
  - OpenModelica/OMSimulator-testsuite#128

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :+1:

**Comment by adeas31** [comment]
Is the TLM position and orientation stored in the SSP?

**Comment by robbr48** [comment]
No, that is not yet implemented. Not sure how to do that. Right now we only forward the values to OMTLMSimulator and then forget about them.

**Comment by adeas31** [comment]
Store it in the annotations.

**Comment by robbr48** [comment]
Ok, I will make sure it is saved and loaded to/from SSD.

**Pull request closed without merging**
