### PR TITLE
Silence C compiler warning

### PR DESCRIPTION
**Pull request by AnHeuermann**
### Related Issues

So many warnings when compiling OMSimulator.

### Purpose

Fixed one of these.

### CODE REVIEW

**Comment by adeas31** [comment]
I m guessing most of the warnings from FMIL.

**Comment by lochel** [comment]
Which warning did you try to fix?

**Comment by AnHeuermann** [comment]
I would have to rebuild to find the exact error. Basically the compiler is complaining about the space behind the percent symbol:  `% `.

More correct would be to pass the string `""` and repeat it `width - pos + 1`-times.
See https://stackoverflow.com/questions/7899119/what-does-s-mean-in-printf

**Comment by lochel** [comment]
Ok, I don't remember why I put a white space in there. Maybe we should even change it to %c: `printf("%*c %3d%%", width - pos + 1, ']', percent);` What do you think?

**Pull request merged**
