### PR TITLE
Log all variables with TLM simulations

### PR DESCRIPTION
**Pull request by robbr48**
### Purpose

Log all variables with TLM simulations.

### Approach

Buffer values in SystemTLM class whenever writeToSockets is called. Update result file on regular logging interval. Wait until all variables are available for the log time, and interpolate backwards if necessary.

### Type of Change

- New feature (non-breaking change which adds functionality)

### Checklist

- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by lochel** [comment]
This means all signals will be logged in the same result file (even for mixed TLM/FMI simulations)? 👍 Great!

**Comment by robbr48** [comment]
Yes, it will log everything with a fixed logging interval. It does not work for external models though, but I think we can live with that for now.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/908//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#527
  - OpenModelica/OMSimulator-testsuite#130

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[ASan:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/908/)** The test suite is unstable. :confused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/909//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#527
  - OpenModelica/OMSimulator-testsuite#130

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[ASan:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/909/)** The test suite is unstable. :unamused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/910//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#527
  - OpenModelica/OMSimulator-testsuite#130

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/912//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#527
  - OpenModelica/OMSimulator-testsuite#130

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[ASan:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/912/)** The test suite is unstable. :confused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/913//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#527
  - OpenModelica/OMSimulator-testsuite#130

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[ASan:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/913/)** The test suite is unstable. :worried:

**Comment by OpenModelica-Hudson** [comment]
**[ASan:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/915/)** The test suite is unstable. :disappointed:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/917//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#527
  - OpenModelica/OMSimulator-testsuite#130

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/918//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#527
  - OpenModelica/OMSimulator-testsuite#130

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/918/)** The test suite is unstable. :unamused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/919//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#527
  - OpenModelica/OMSimulator-testsuite#130

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :blush:

**Pull request closed without merging**
