### PR TITLE
Generate connectors for CS-FMUs

### PR DESCRIPTION
**Pull request by lochel**
### Purpose

Generate connectors for CS-FMUs

### Approach

Read ModelDescription.xml of CS-FMUs

### Type of Change

- New feature (non-breaking change which adds functionality)

### Checklist

- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by lochel** [comment]
Importing the connectors is still missing.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/696//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#403
  - OpenModelica/OMSimulator-testsuite#94

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[ASan:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/696/)** The test suite is unstable. :worried:

**Comment by OpenModelica-Hudson** [comment]
**[ASan:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/697/)** The test suite is unstable. :unamused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/698//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#403
  - OpenModelica/OMSimulator-testsuite#94

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :bowtie:

**Pull request closed without merging**
