### PR TITLE
Remove instantiate button documentation

### PR DESCRIPTION
**Pull request by adeas31**
### Related Issues

https://github.com/OpenModelica/OpenModelica/issues/6258
https://github.com/OpenModelica/OpenModelica/pull/7101

### Purpose

Better documentation

### Approach

Removes the obsolete instantiate button documentation.

### CODE REVIEW

**Review by lochel — APPROVED** [review]
LGTM - @adrpo I just don't know why jenkins is complaining....

**Comment by adrpo** [comment]
I have no idea either. Seems that alpine linux docket has been updated and the new one has errors.
@AnHeuermann do we need this stage or should we just remove it?

**Comment by AnHeuermann** [comment]
On my last PR it worked after a few tries.
I'm not sure who added the alpine stage to Jenkins. I guess @sjoelund ?
But we could disable it for now.

**Comment by lochel** [comment]
@adeas31 I moved your commit to a dedicated pull request because the only available merge option (on purpose) is "squash and merge". Thanks!

**Comment by sjoelund** [comment]
alpine used FROM alpine:edge. Perhaps it can be changed to the previous alpine release (alpine:3.11 or alpine:3.12) instead since it seems they broke something in the latest one. It's a quite good target to test since embedded systems might not use the huge GNU libc.

**Pull request merged**
