### PR TITLE
Enable tlm tests again

### PR DESCRIPTION
**Pull request by lochel**
This reverts partially aca92db88f8d6a8f8cc4950a18792d030548a7ac.

### CODE REVIEW

**Comment by sjoelund** [comment]
Seems you got a machine with the hostname issue we talked about earlier

**Comment by lochel** [comment]
Is that fixed now?

**Comment by sjoelund** [comment]
Should be

**Comment by sjoelund** [comment]
Wouldn't it be simple to keep the flag though? But keep the default value of the parameter as empty?

**Comment by lochel** [comment]
@robbr48 Some tlm tests are still failing. Can you please have a look?

**Comment by robbr48** [comment]
@sjoelund @lochel 
The segmentation fault occurs on the following line (TLMClientComm.cc, 210):
    `memcpy((char *)&sa.sin_addr, hp->h_addr, hp->h_length);`
Where `hp` is obtained from
    `hp = gethostbyname(callname.c_str());`
Can it be related to the other problem with `gethostbyname()`?

**Comment by sjoelund** [comment]
What is `callname.c_str()` in this case? I first suspected this could be that you do `gethostbyname()` and get an INET6 address, but it should only return INET4 addresses...
The only thing I could think of is if `hp->h_addr` is NULL, which is not checked.

**Comment by robbr48** [comment]
`callname.c_str()` is printed to the logfile and looks ok. In this case it is "127.0.0.1". I also printed `hp->h_addr`, and it is not NULL. I'm thinking that it could have something to do with thread safety, since multiple threads are calling `gethostbyname` in parallel. Perhaps it is not thread safe.

**Comment by sjoelund** [comment]
Yes, `gethostbyname` is marked thread-unsafe in the man-pages (`MT-Unsafe race:hostbyname env locale`)
`gethostbyname_r` exists but is a bit trickier to use it seems (and is a GNU extension).

**Comment by sjoelund** [comment]
If you know the string is just an IPv4 address and never a hostname, you could also use `inet_addr()` instead.
You could also
* Create a global lock for the host lookup
* Lookup all host names before creating the threads

**Comment by robbr48** [comment]
Ok, I solved it by adding mutex locks, since it should be possible to use hostnames (#623)

**Comment by lochel** [comment]
The tlm tests are unfortunately still unstable:
```bash
+ tlm1d.lua ... execution failed

==== Log /tmp/oms-rtest-unknown/tlmtmp_5773/log-tlm1d.lua
Starting TLM simulation.
Monitoring thread finished.
Fatal error: Failed to send message header. Aborting.
info: Logging information has been saved to "tlm1d.log"
```

**Comment by robbr48** [comment]
@lochel Yes, that's a different error. It should be solved now by OpenModelica/OMTLMSimulator#112

**Comment by lochel** [comment]
The test tlm1d.lua is failing with a segmentation fault.

```bash
+ tlm1d.lua ... execution failed

==== Log /tmp/oms-rtest-unknown/tlmtmp_9083/log-tlm1d.lua
Segmentation fault (core dumped)
```

**Pull request merged**
