### PR TITLE
Updated embrace use case

### PR DESCRIPTION
**Pull request by robha67**
### Related Issues
Updated use-case with a simulink generated SW FMU. The use-case now include "bus-to-bus" type connections including a int to enum connection. 

### Purpose
Open test platform capturing end-user requirements on OMSimulator

### CODE REVIEW

**Comment by lochel** [comment]
Sorry, this was closed by accident.

**Comment by lochel** [comment]
@robha67 Sorry that it took so long, but now the example is adapted to the test suite setup and should hopefully pass all checks.

**Comment by lochel** [comment]
@robha67 I had to reduce the stopTime from 1200 to 12 in order to make the test pass in reasonable time. Please let me know if you see any problem with that.

**Comment by robha67** [comment]
I could imagine that the longer time step could cause some instability problems and erranous results. Is the OM simulator checked for numerical stability? If not, then I don't see a problem. @lochel

**Comment by lochel** [comment]
I didn't change the step size. The simulation just terminates at stopTime=12 instead of stopTime=1200 because the test case otherwise takes way too much time.

**Comment by robha67** [comment]
Oh, ok. Then I missunderstood you. I see no reason to run the entire mission. I guess a longer simulation is needed to se the effect concerning the potential issue of increasing overhead but I believe that investigation is best done "off-line"

**Pull request merged**
