### PR TITLE
Fix load path for OMSimulator for Python

### PR DESCRIPTION
**Pull request by AnHeuermann**
### Related Issues
Running 
```python
>>> from OMSimulator import OMSimulator
>>> oms = OMSimulator()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aheuermann1/OMSimulator-dev-158/lib/OMSimulator.py", line 8, in __init__
    self.obj=cdll.LoadLibrary("libOMSimulator.so")
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libOMSimulator.so: cannot open shared object file: No such file or directory
>>> from OMSimulator import OMSimulator
>>> oms = OMSimulator()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aheuermann1/OMSimulator-dev-158/lib/OMSimulator.py", line 8, in __init__
    self.obj=cdll.LoadLibrary(dllName)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libOMSimulator.so: cannot open shared object file: No such file or directory
```
can fail if:
-  OMSimulator was build toghether with OpenModelica (different folder structure)

or

-  The current directory is not the location where libOMSimulator.so is stored.

### Purpose
Make OMSimulator usable from Python without hacking our files.

### Approach
  - Load path gets set by CMake during build.
    This should work when building OMSimulator with and without
    OpenModelica.
  - It's now possible to give a custom dynamic library for OMSimulator.
    ```python
    >>> from OMSimulator import OMSimulator
    >>> oms = OMSimulator()
    >>> oms_specific_version = OMSimulator("/path/to/libOMSimulator.so")
    ```

Thanks @superlou.
I extended the way you changed your files described in https://github.com/OpenModelica/OMSimulator/issues/772.

### CODE REVIEW

**Comment by superlou** [comment]
Thinking about steps to make the Python bindings more Pythonic like in #777, I was wondering if we see any other build-specific configuration steps in the Python file? Could we simplify the Python-binding development process by simply having the class first look for matching libs in its own directory, then see if someone has specified a `lib` parameter? That would remove the need to have any compile-time processing of the Python bindings. Since OMSimulator instances are made so rarely, there's no significant performance gain had by trying to guess the lib at compile time.

**Comment by AnHeuermann** [comment]
I'm not sure if I understand you correctly. But depending on the way OMSimulator is build the lib will lie right next to it (if you build OMSimulator as a independent project) or in a subdirectory (if you build it with the OpenModelica superproject). So we need to add this in some sort to the loading.

And `self.obj=cdll.LoadLibrary(os.path.join(dirname, "@OMSIMULATORLIB_DIR_STRING@", "@OMSIMULATORLIB_STRING@"))` should contain the correct location of the dynamic C library after build. So there is no guessing.

But you can change this in #777 if you like. For now I would like to merge this PR.

**Comment by superlou** [comment]
I agree with merging the PR as is (though I haven't tested it myself).

I was just thinking that down the road it might be nice to not need a compile step at all for the python code, i.e. removing `@OMSIMULATORLIB_DIR_STRING@` and `@OMSIMULATORLIB_STRING@` and using a little bit of Python logic to check for a lib file in the file directory.

**Comment by AnHeuermann** [comment]
Ah, now I get it. Yes that would be possible.

**Comment by lochel** [comment]
Thanks for the discussion and contribution. Feel free to come up with another PR for further improvements.

**Pull request merged**
