### PR TITLE
 Add support for binNormal to mat reader

### PR DESCRIPTION
**Pull request by lochel**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
**[Mac:](https://test.openmodelica.org/hudson/job/OMSimulator-PR-MacOSX/98//console)** The job failed to compile. :worried:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being tested. It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#115
  - OpenModelica/OMSimulator-testsuite#23

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :bowtie:

**Comment by sjoelund** [comment]
Any reason why we don't simply share the code with the OMC matlab reader?

**Comment by lochel** [comment]
We do share the underlying reading/writing functionality (maybe still not in all places?). But the API on top of it is quite adapted to the c runtime data structures. I suggested already several times to make a c library with auxiliary functions, like result file writing/reading/comparison and maybe other stuff that can be shared.

**Pull request closed without merging**
