### PR TITLE
Implement ME mode

### PR DESCRIPTION
**Pull request by lochel**
### Purpose

This implements support for model exchange FMUs.

### Approach

Model exchange FMUs can be added and connected within strongly connected systems. The strongly connected system provides a common solver for all its model exchange FMUs.

### Type of Change

- Code refactoring (non-breaking change which improves maintainability)
- New feature (non-breaking change which adds functionality)

### Checklist

- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/837//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#480
  - OpenModelica/OMSimulator-testsuite#120

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/837/)** The test suite is unstable. :cry:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/838//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#480
  - OpenModelica/OMSimulator-testsuite#120

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[ASan:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/838/)** The test suite is unstable. :confused:

**Comment by lochel** [comment]
@robbr48 ASAN is still complaining about `tlmsignals.lua`, can you please have a look?

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/839//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#480
  - OpenModelica/OMSimulator-testsuite#120

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :blush:

**Pull request closed without merging**
