### PR TITLE
Model Exchange mode for FMI simulator

### PR DESCRIPTION
**Pull request by lochel**
### Related Issues

#173
OpenModelica/OMSimulator-testsuite#66

### Purpose

New functionality to make it possible to define solvers and connect them to FMUs. It will be possible to assign a solver to multiple FMUs (strong coupling).

```Lua
-- instantiate FMUs
oms2_addFMU("DualMassOscillator", "../FMUs/DualMassOscillator.System1_me.fmu", "System1")
oms2_addFMU("DualMassOscillator", "../FMUs/DualMassOscillator.System2_me.fmu", "System2")

-- instantiate solvers
oms2_addSolver("DualMassOscillator", "solver1", "CVODE")

-- connect solvers
oms2_connectSolver("DualMassOscillator", "System1", "solver1")
oms2_connectSolver("DualMassOscillator", "System2", "solver1")
```

### Type of Change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

### Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/487//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#275
  - OpenModelica/OMSimulator-testsuite#71

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/487/)** The test suite is unstable. :worried:

**Comment by lochel** [comment]
For some reason, all OMSysIdent test cases fail. @bernhard-thiele can you please have a look?

**Comment by bernhard-thiele** [comment]
I will give it a try

**Comment by lochel** [comment]
Yes, indeed. I forgot to initialize `startTime` properly.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/488//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#275
  - OpenModelica/OMSimulator-testsuite#71

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/488/)** The test suite is unstable. :-1:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/489//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#275
  - OpenModelica/OMSimulator-testsuite#71

**Comment by OpenModelica-Hudson** [comment]
**[Windows-GCC:](https://test.openmodelica.org/hudson//job/OMSimulator-PR-Windows/334)** The test suite is unstable. :confused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/490//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#275
  - OpenModelica/OMSimulator-testsuite#71

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :smile:

**Pull request closed without merging**
