### PR TITLE
New API oms2_getFMUPath()

### PR DESCRIPTION
**Pull request by adeas31**
Add FMU path to `oms_component_t`

### CODE REVIEW

**Comment by lochel** [comment]
The `oms_component_t` is also used for constant values, ports, and lookup tables. Therefore, I am not sure if we should save the path in the component structure.

**Comment by adeas31** [comment]
In that case the path could be empty. We can anyway distinguish about it from `oms_component_type_enu_t`.

**Comment by lochel** [comment]
Sure, that is possible. But that would probably be inconsistent. Other sub-models have other characteristic attributes. We should either add all the different attributes to `oms_component_t` or none of them. I prefer to have a function to get the fmu path, e.g. `oms2_getFMUPath(const char* cref, const char** path)`.

**Comment by adeas31** [comment]
OK. I am fine with a separate function. Will you add it or should I just update in this same PR?

**Comment by lochel** [comment]
It would be nice if you update this PR.

**Comment by adeas31** [comment]
Should be fine to merge now.

**Pull request merged**
