### PR TITLE
Added cmake based build system alternative

### PR DESCRIPTION
**Pull request by bernhard-thiele**
Added a cmake based build process in addition to the Makefile based build process.
One can use either of the two.

### CODE REVIEW

**Comment by bernhard-thiele** [comment]
I renamed the library target and link the  OMSimulator executable to the static version of the library

**Comment by lochel** [comment]
I guess we can also remove the previously used makefiles. We should try to improve this a bit more before merging. There are at least some issues on Windows. @mahge will have a look.

**Comment by sjoelund** [comment]
The shared and static library should always have the same name. Anything else is a nightmare for linking against the library (need multiple rules and priority between them). Please keep the names the same and solve it by using `-Wl,-Bstatic -lomsim -Wl,-Bdynamic` or however this is done in cmake.

**Comment by lochel** [comment]
The best would be if the libs are called `libOMSimulator.{a,so}` (and maybe `libOMSimulator.{lib,dll}` on Windows?).

**Comment by bernhard-thiele** [comment]
If you specify a library target name `OMSimulator` in cmake, it will automatically use the name `libOMSimulator.{a,so}` on Linux and `OMSimulator.{lib,dll}` in Windows.

Regarding using the same for shared and static libraries. This should be possible (http://public.kitware.com/pipermail/cmake/2006-May/009201.html), but the problem is that this is not a common approach for Windows. If one creates a DLL using Visual C one often has a a static library of the same name, but this library is just an import library for the DLL. So I'm not sure how to handle this best. It's also an option to add some logic to use the same name if one compiles for Linux, but a different name if one compiles for Windows.

**Comment by bernhard-thiele** [comment]
Maybe I  should have also mentioned that if one doesn't specify whether one wants to build a static or shared library, cmake uses a (global) flag `BUILD_SHARED_LIBS` for deciding which type of library to build. This flag can be made an option that a user can set before building. However, my thinking was to always build both versions of the library.

**Comment by bernhard-thiele** [comment]
I took the branch from @mahge that does without external project. I think that is the most robust solution for now. Still I think one should keep the external project approach in mind. But let's go forward...

**Pull request merged**
