### PR TITLE
export unique ssp

### PR DESCRIPTION
**Pull request by arun3688**
### Purpose

This PR fix tests to export unique ssp's

### CODE REVIEW

**Review by lochel — APPROVED** [review]
The test is not testing much though, right?

**Comment by arun3688** [comment]
> The test is not testing much though, right?

Yes it does not test much, just to avoid conflicts with jenkins testing

**Comment by lochel** [comment]
I meant the original test which is just checking the return value and not the actual export.

**Comment by lochel** [comment]
I meant the original test which is just checking the return value and not the actual export.

**Pull request merged**
