### PR TITLE
New flag --wallTime

### PR DESCRIPTION
**Pull request by lochel**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/1037//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#592

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/1037/)** The test suite is unstable. :cry:

**Comment by lochel** [comment]
@robbr48 TLM tests are again failing randomly. Can you please have a look again?

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/1038//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#592

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/1042//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#592

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/1042/)** The test suite is unstable. :cry:

**Comment by lochel** [comment]
@robbr48 see #596

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/1047//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#592

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Windows-GCC:](https://test.openmodelica.org/hudson//job/OMSimulator-PR-Windows/712)** The test suite is unstable. :confused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/1048//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#592

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :tada:

**Pull request closed without merging**
