### PR TITLE
Issue 231 233 lua tlm loglevel samples

### PR DESCRIPTION
**Pull request by robbr48**
### Related Issues

#231 and #233 

### Purpose

We need to control log level and number of data samples in TLM simulations.

### Approach

Added lua functions for above mentioned features.

### Type of Change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

### Checklist

- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- My changes generate no new warnings

### CODE REVIEW

**Comment by lochel** [comment]
What about the Python interface?

**Comment by robbr48** [comment]
@lochel We need to implement all TLM functions for the Python interface.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/411//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#234

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :raised_hands:

**Pull request closed without merging**
