### PR TITLE
 Implement oms3_getSubModelPath and oms3_getFMUInfo

### PR DESCRIPTION
**Pull request by lochel**
### Type of Change

- Code refactoring (non-breaking change which improves maintainability)
- New feature (non-breaking change which adds functionality)

### Checklist

- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by lochel** [comment]
I expected it to be filled actually. I will look into it.

**Comment by lochel** [comment]
I had to change the implementation a bit, because the oms2 implementation had required to instantiate the FMUs before populating the FMU information.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/706//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#409

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :raised_hands:

**Pull request closed without merging**
