### PR TITLE
Issue 1101

### PR DESCRIPTION
**Pull request by AnHeuermann**
### Related Issues

#1101

### Purpose

Resolve compiler errors with `setsockopt` on Windows.
Also fix some compiler warnings.

### CODE REVIEW

**Comment by AnHeuermann** [comment]
Did I introduce a new memory leak in https://github.com/OpenModelica/OMTLMSimulator?

**Comment by AnHeuermann** [comment]
@adrpo Do you know if the CI fails because of https://github.com/OpenModelica/OMTLMSimulator/pull/130 or because of https://github.com/OpenModelica/OMTLMSimulator/pull/131?

**Comment by AnHeuermann** [comment]
The linux64-asan tlm3d.lua test was stuck (around an hour running and not stopped) in the last two Jenkins runs. I tried it with the same docker image on my machine a few times and it was always working. It is by far the slowest test (~50 seconds).

**Comment by adrpo** [comment]
The problem is that asan consumes all memory (20t !!) on the machine and everything breaks, see discussion in #1100. When I limit the memory to 6GB *all* tests are failing.

**Comment by adrpo** [comment]
Is strongly suggest to ulimit -v to 10gb or so max and maybe disable the asan tests.

**Comment by sjoelund** [comment]
It's only virtual memory, so it's not actually using 20T. Only pages that are written to start using actual memory. But that's the way ASAN works. If you limit memory it will fail, no matter what limit under 20T... Maybe use valgrind instead?

**Comment by AnHeuermann** [comment]
Okay, so now I understand why the runs happen to break so often.

I don't think there is any point in checking for memory problems in our CI if it breaks it every second run.

**Pull request merged**
