### PR TITLE
Use reasonable default values for geometry

### PR DESCRIPTION
**Pull request by adeas31**

### CODE REVIEW

**Comment by lochel** [comment]
The geometry information is optional and treated as undefined if `y1 == y2`. OMEdit should override it immediately when creating new objects.

**Comment by adeas31** [comment]
Yeah but when OMEdit is reading the value it should get a reasonable default instead of 0.

**Comment by lochel** [comment]
We can make it returning a NULL pointer if actually no information is specified. But I guess OMEdit can handle `y1 == y2` as unspecified though.

**Comment by adeas31** [comment]
So is basically undefined even when `x1 == x2`.

**Comment by lochel** [comment]
I would treat it as undefined if a component's area is zero, i.e. `y1 == y2 || x1 == x2`.

**Comment by lochel** [comment]
Okay, I will make it optional and returning a NULL pointer if undefinied.

**Pull request merged**
