### PR TITLE
Fix various memory errors for TLM systems

### PR DESCRIPTION
**Pull request by robbr48**
### Purpose

Fix memory errors causing TLM tests to fail.

### Approach

- Replace assignment with comparison operator
- Increase 3D flow variable array from 3 to 6
- Make sure to use actual (lowest level) TLM bus
- Write correct effort variables to log file

### Type of Change

- Bug fix (non-breaking change which fixes an issue)

### Checklist

- I have performed a self-review of my own code
- My changes generate no new warnings

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/991//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#566

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[ASan:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/991/)** The test suite is unstable. :-1:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/992//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#566

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/994//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#566

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Windows-GCC:](https://test.openmodelica.org/hudson//job/OMSimulator-PR-Windows/674)** The test suite is unstable. :worried:

**Comment by lochel** [comment]
> **[Windows-GCC:](https://test.openmodelica.org/hudson//job/OMSimulator-PR-Windows/674)** The test suite is unstable. 😟

This is weird... 😕

**Comment by lochel** [comment]
@robbr48 I think you need to manually rebase the changes. For some reason, Hudson is doing it badly.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/999//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#566

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :raised_hands:

**Pull request closed without merging**
