### PR TITLE
Fixing 32bit MINGW tests

### PR DESCRIPTION
**Pull request by AnHeuermann**
- Adding 32bit platforms for Win32 and Linux32 using Docker
  - Adding/Updating 32bit FMUs with omc version v1.16.2
  - Removing log and summary files from FMUs

### Related Issues

Closing #902

### CODE REVIEW

**Comment by AnHeuermann** [comment]
`oms_setTempDirectory("./someDir/")` is not working with my mingw32 build of OMSimulator.
I can debug up to `std::filesystem::create_directory` in [Scope.cpp#L239](https://github.com/OpenModelica/OMSimulator/blob/master/src/OMSimulatorLib/Scope.cpp#L239) and there it will fail with an `__cxa_trow`.
Since all tests use `oms_setTempDirectory` they are all failing.

If I replace `oms_setTempDirectory("./someDir/")` with `oms_setTempDirectory("./someDir")` (minus the slash `/`) it works.
It is an gcc vs. clang problem, see [this StackOVerflow question](https://stackoverflow.com/questions/60130796/return-value-of-stdfilesystemcreate-directories-on-paths-with-trailing-sla).

**Comment by lochel** [comment]
Should we then just trim a trailing slash in oms_setTempDirectory?

**Comment by AnHeuermann** [comment]
That's what I did. I'm adding a lable for MINGW32 at the moment so I don't have to restart this Jenkins job every time.

**Comment by AnHeuermann** [comment]
The test are running on my machine using MINGW32 with no additional settings (`clang` and `clang++`) and if I build with `gcc` and `g++`. I can't see what the error on Jenkins is.

In the [log of buildOMS()](https://test.openmodelica.org/jenkins/blue/rest/organizations/jenkins/pipelines/OMSimulator/branches/PR-903/runs/4/nodes/88/steps/237/log/?start=0) we have:
```
set MSYSTEM=MINGW64 
```
and
```
c:\dev\jenkins\ws\OMSimulator_PR-903>C:\OMDev\tools\msys\usr\bin\sh --login -i -c "cd `cygpath 'c:\dev\jenkins\ws\OMSimulator_PR-903'` && chmod +x buildOMSimulatorWindows.sh && ./buildOMSimulatorWindows.sh && rm -f ./buildOMSimulatorWindows.sh" 
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
```
That's not looking correct.

**Comment by AnHeuermann** [comment]
> The test are running on my machine using MINGW32 with no additional settings (`clang` and `clang++`) and if I build with `gcc` and `g++`. I can't see what the error on Jenkins is.
> 
> In the [log of buildOMS()](https://test.openmodelica.org/jenkins/blue/rest/organizations/jenkins/pipelines/OMSimulator/branches/PR-903/runs/4/nodes/88/steps/237/log/?start=0) we have:
> 
> ```
> set MSYSTEM=MINGW64 
> ```
> 
> and
> 
> ```
> c:\dev\jenkins\ws\OMSimulator_PR-903>C:\OMDev\tools\msys\usr\bin\sh --login -i -c "cd `cygpath 'c:\dev\jenkins\ws\OMSimulator_PR-903'` && chmod +x buildOMSimulatorWindows.sh && ./buildOMSimulatorWindows.sh && rm -f ./buildOMSimulatorWindows.sh" 
> sh: cannot set terminal process group (-1): Inappropriate ioctl for device
> sh: no job control in this shell
> ```
> 
> That's not looking correct.

That's now fixed as well

**Comment by adrpo** [comment]
This is because you login via sh into something that is no a terminal, harmless:
```
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
```

**Review by lochel — APPROVED** [review]
LGTM

**Pull request merged**
