### PR TITLE
Source code for TLM reference FMUs

### PR DESCRIPTION
**Pull request by robbr48**
### Purpose

Add source code to reference FMUs for TLM.

### Approach

Source code for hand-written FMUs, together with a brief instruction, is added to `resources` folder.

Source code for adder and source FMUs are added to their respective folder. Unfortunately their original .mo files are no longer available.

Source code added in this PR:

- tlm.CoarseGrained1_1D
- tlm.CoarseGrained2_1D
- tlm.FineGrained1_1D
- tlm.FineGrained2_1D
- tlm.LowerPendulumFG
- tlm.UpperPendulumFG
- tlm.adder
- tlm.source

Source code already available as .mo or .mos files:

- tlm.LowerPendulum
- tlm.UpperPendulum
- tlm.mass
- tlm.massSpring

Source code no longer available (needs to be recreated):
- tlm.gain

@arun3688 I cannot add you as a reviewer, is this what you need?

### CODE REVIEW

**Comment by arun3688** [comment]
@robbr48 actually i needed only the mo files or mos files, Because it is easier to generate windows binaries. Adding the source code will not help much to run the fmu's from windows.

**Comment by lochel** [comment]
As far as I know, there are no mo/mos files for all of these FMUs. @robbr48 implemented them himself to add non-standard functionality.

**Comment by arun3688** [comment]
No there are some mo files existing for some fmus "tlm.LowerPendulum , tlm.UpperPendulum tlm.mass and tlm.massSpring"

**Comment by robbr48** [comment]
@arun3688 I no longer have the mo/mos files for tlm.adder, tlm.source and tlm.gain. The coarse grained, fine grained and pendulum examples are all written by hand in plain C++ and must be compiled manually.

**Pull request closed without merging**
