### PR TITLE
 Introduce targets to configWinVS.bat

### PR DESCRIPTION
**Pull request by lochel**
## Purpose

This provides targets to configWinVS.bat to execute a certain step of the configuration process.

E.g. `> configWinVS.bat VS15-Win64 boost`

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/377//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#213
  - OpenModelica/OMFMISimulator-3rdParty#21

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/377//console)** The job failed to compile. :unamused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/378//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#213
  - OpenModelica/OMFMISimulator-3rdParty#21

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/378//console)** The job failed to compile. :-1:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/379//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#213
  - OpenModelica/OMFMISimulator-3rdParty#21

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/379//console)** The job failed to compile. :confused:

**Comment by lochel** [comment]
This is also about fixing #214.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/380//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#213
  - OpenModelica/OMFMISimulator-3rdParty#21

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/380//console)** The job failed to compile. :disappointed:

**Comment by lochel** [comment]
@robbr48 Where do I have to fix the paths inside the OMTLMSimulator?

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/381//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#213
  - OpenModelica/OMFMISimulator-3rdParty#21
  - OpenModelica/OMTLMSimulator#79

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Windows-MSVC:](https://test.openmodelica.org/hudson/job/OMSimulator-PR-Windows/238//console)** The job failed to compile. :cry:

**Comment by OpenModelica-Hudson** [comment]
**[Windows-MSVC:](https://test.openmodelica.org/hudson/job/OMSimulator-PR-Windows/240//console)** The job failed to compile. :worried:

**Comment by OpenModelica-Hudson** [comment]
**[Windows-MSVC:](https://test.openmodelica.org/hudson/job/OMSimulator-PR-Windows/242//console)** The job failed to compile. :disappointed:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/382//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#213
  - OpenModelica/OMFMISimulator-3rdParty#21
  - OpenModelica/OMTLMSimulator#79

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :raised_hands:

**Pull request closed without merging**
