### PR TITLE
Fix linking error for MSVC

### PR DESCRIPTION
**Pull request by sjoelund**
This should fix the linking error I introduced.

### CODE REVIEW

**Comment by lochel** [comment]
@sjoelund Apparently, the Windows build is still broken. Can you have a look?

**Comment by sjoelund** [comment]
The new error seems to be related to the OMFitLib subproject. I didn't touch any file that should influence that.

**Comment by lochel** [comment]
That's weird. It compiles even fine on my system. @bernhard-thiele Can you have a look?

**Comment by sjoelund** [comment]
It could have to do with not running the ceres dependencies, but in that case the MSVC job simply needs to compile that (or properly disable CERES in the cmake project for MSVC).

**Comment by lochel** [comment]
I've build the project with OMFit.

**Pull request merged**
