### PR TITLE
Updated test FMUs with OpenModelica v1.18.0-dev.192

### PR DESCRIPTION
**Pull request by AnHeuermann**

### CODE REVIEW

**Comment by lochel** [comment]
What version of OpenModelica did you use? 1.17.0 is already too old. It should be OMCompiler v1.18.0-dev.171+gc263934f53 or never.

**Comment by lochel** [comment]
And did you do the submodule updates on purpose or by mistake?

**Comment by AnHeuermann** [comment]
> What version of OpenModelica did you use? 1.17.0 is already too old. It should be OMCompiler v1.18.0-dev.171+gc263934f53 or never.

Then I'll use todays master.

> And did you do the submodule updates on purpose or by mistake?
Dang it...

**Review by lochel — APPROVED** [review]
Looks good with all the warnings gone 😃

**Comment by AnHeuermann** [comment]
There is one change in https://github.com/OpenModelica/OMSimulator/pull/999/files#diff-3e28691a2c7245ed9450a4ec5db2a2633eda524f6c05791acfdacdb50e4e3709L138-R123.
The values of `limiter.u` and `limiter.y` changed by `0.1`.

**Comment by lochel** [comment]
Which test case is it? Your link doesn't work for me.

**Comment by AnHeuermann** [comment]
testsuite/OMSimulator/PI_Controller.lua

**Comment by lochel** [comment]
I guess you refer to `PI_Controller.lua`. This is fine. The new results are better due to proper initialization 👍

**Comment by AnHeuermann** [comment]
AircraftVehicleDemonstrator is failing, but I didn't change that FMUs.
Any ideas @lochel?

**Comment by lochel** [comment]
Those FMUs don't run on 32bit Windows. However, I have no clue why it also failed on 64bit Windows....

**Comment by arun3688** [comment]
@AnHeuermann I tested your PR in my computer and the AircraftVehicleDemonstrator worked for me

**Comment by AnHeuermann** [comment]
Now it worked. Should we merge it?

**Comment by lochel** [comment]
@adrpo, @sjoelund It seems that the test behaviour different on different Windows machines in our jenkins cluster.

**Comment by sjoelund** [comment]
> @adrpo, @sjoelund It seems that the behaviour is different on different Windows machines in our jenkins cluster.

So it fails on the real Windows and succeeded on the virtual machine?

**Comment by AnHeuermann** [comment]
Do we have some time limits for the test? The AircraftVehicleDemonstrator test is slow:
On my Windows with OMDev and OMSimulator build as standalone I need around 215 seconds with both clang and gcc.
But both are working.

**Comment by adrpo** [comment]
Testing using rtest on windows machines is really very unreliable. rtest hangs sometimes, other issues pop up, etc.

**Comment by adrpo** [comment]
For example, on windows OMSimulator hanged 20 hours already. In general is perl that hangs running rtest and you need to kill it manually.
https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OMSimulator/detail/PR-999/2/pipeline

**Comment by arun3688** [comment]
@AnHeuermann I did not measure the time, but in my computer also it took close to 5 minutes to finish

**Comment by lochel** [comment]
I think the problem here is more related to numeric. The example finished in both cases, but with slightly different numeric results. So it might be a different boost version or any other lib?! Not really sure though.

**Pull request merged**
