### PR TITLE
Swap arguments of oms2_saveModel

### PR DESCRIPTION
**Pull request by lochel**
### Purpose

Swap arguments of oms2_saveModel, since most other functions use also the cref as first argument.

### Type of Change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

### Checklist

- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/543//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#313
  - OpenModelica/OMSimulator-testsuite#75

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :raised_hands:

**Comment by adeas31** [comment]
The same should be done for `oms2_loadModel` and `oms2_loadModelFromString`.

**Comment by lochel** [comment]
Not quite sure, because there the cref is actually a return value.

**Pull request closed without merging**
