### PR TITLE
Fix oms2::Model::terminate

### PR DESCRIPTION
**Pull request by lochel**

### CODE REVIEW

**Comment by lochel** [comment]
@robbr48 This looks like an issue inside the TLM simulator that shows up randomly.

**Comment by robbr48** [comment]
I guess so, since it only happens with TLM models. This may have been fixed by my latest memory fixes. For example I added mutex locks when deleting pointers used by multiple threads, to avoid double freeing. It is hard to tell without knowing the origin of the problem though.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/339//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#180

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/339//console)** The job failed to compile. :confused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/340//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#180

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/340//console)** The job failed to compile. :confused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/342//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#180

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/342//console)** The job failed to compile. :unamused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/343//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#180

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/343//console)** The job failed to compile. :disappointed:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/355//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#180

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/355//console)** The job failed to compile. :worried:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/359//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#180

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :smile:

**Pull request closed without merging**
