### PR TITLE
fix OMSimulator pip package

### PR DESCRIPTION
**Pull request by arun3688**
### Related Issues

https://github.com/OpenModelica/OMSimulator/issues/1283

### Purpose

This PR fixes the `OMSimulator pip package` according to the new cmake build system.

### TODO

- [x] fix the setup.py file to copy the dlls according to the new build path

### CODE REVIEW

**Comment by arun3688** [comment]
@bilderbuchi i did a quick test in OMEdit and it works for me 

image

this is my omc version `v1.24.0-dev-223-g596b7d3d68-cmake`

**Comment by arun3688** [comment]
@bilderbuchi i think you are somehow having the old version of omsimulator, the current version of omsimulator checks for 3 directories up see the below code in 

```
    if not os.path.exists(omslib):
      if os.name == 'nt': # Windows
        omslib = os.path.join(dirname, "../../../bin", "libOMSimulator.dll")
        dllDir = os.add_dll_directory(os.path.dirname(omslib))
        dllSearchPath = True
      else:
        # attempt to fix #8163 on Linux
        omslib = os.path.join(dirname, "..", "libOMSimulator.dll")
```
please make sure in your installed path` C:\\OpenModelica1.24.0-dev-64bit\\lib\\omc\\OMSimulator\\capi.py` in l`ine number :13` , you should have the above code otherwise you are having older version of omsimulator

**Comment by bilderbuchi** [comment]
No, I have
```python
    ## look for dll in the OpenModelica top level directory or OMSimulator stand alone directory
    if not os.path.exists(omslib):
      if os.name == 'nt': # Windows
        omslib = os.path.join(dirname, "../../bin", "libOMSimulator.dll")
        dllDir = os.add_dll_directory(os.path.dirname(omslib))
        dllSearchPath = True
      else:
        # attempt to fix #8163 on Linux
        omslib = os.path.join(dirname, "..", "libOMSimulator.dll")
```
I installed with the [nightly installer](https://build.openmodelica.org/omc/builds/windows/nightly-builds/64bit/OpenModelica-v1.24.0-dev-230-g20a061263e-64bit.exe) from today. 

I see some templating going on in
https://github.com/OpenModelica/OMSimulator/blob/6f4ecda63323675c4c0aed70f6e31319e7e80771/src/OMSimulatorPython/capi.py#L15
I'm guessing this is replaced during packaging the pip package, or at install time? Something going wrong with `OMSIMULATOR_PYTHON_RELATIVE_DLL_DIR`?

**Comment by bilderbuchi** [comment]
> For now in your `capi.py ` just change to this `omslib = os.path.join(dirname, "../../../bin", "libOMSimulator.dll")` and it should work fine i will fix the cmake file

Yes, that's what I did. Thanks!

**Comment by bilderbuchi** [comment]
> i will fix the cmake file

Should I create a separate ticket for tracking this, does that help you?

**Comment by arun3688** [comment]
@bilderbuchi it would be good if you can create a seperate ticket

**Pull request merged**
