### PR TITLE
boost::filesystem::unique path doesn't exist in boost < 1.45

### PR DESCRIPTION
**Pull request by adrpo**
### Purpose

- attempt to fix Linux nightly builds
- provide alternative implementation in oms_unique_path
- rename oms2_* from OMBoost.* to oms_

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/626//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#369
  - OpenModelica/OMFMISimulator-3rdParty#100

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/627//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#369
  - OpenModelica/OMTLMSimulator#100

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :raised_hands:

**Comment by lochel** [comment]
@adrpo Thanks, that was also on my list. 👍

**Comment by adrpo** [comment]
@lochel: no worries, i got good at porting stuff to older distributions :)

**Pull request closed without merging**
