### PR TITLE
Add support for VS 2017

### PR DESCRIPTION
**Pull request by lochel**
Boost 1.63 doesn't fully support VS2017. I am not sure how to deal with it. Maybe we can get remove the dependency to Boost.

### CODE REVIEW

**Comment by lochel** [comment]
Here is a workaround to compile Boost 1.63 with VS 2017: https://social.msdn.microsoft.com/Forums/en-US/185d7034-77ed-4394-b1e9-c8f6fb819034/adding-boost-to-a-vs2017-project?forum=visualstudiogeneral
However, I haven't tried it yet.

**Comment by hyumo** [comment]
It would be great if Boost dependency could be removed. Incrementing Boost version could also be an option. VS2017 prebuilt binaries are available starting from [Boost 1.64](https://sourceforge.net/projects/boost/files/boost-binaries/1.64.0/)

**Comment by lochel** [comment]
@hyumo I cannot find the VS2017 binaries. However, upgrading the boost libraries causes other issues on Linux, as I remember from a discussion with @sjoelund.

**Comment by hyumo** [comment]
@lochel I think msvc-14.1(VS2017) binaries are available in the 1.64 prebuilt list see [32bit](https://sourceforge.net/projects/boost/files/boost-binaries/1.64.0/boost_1_64_0-msvc-14.1-32.exe/download)/[64bit](https://sourceforge.net/projects/boost/files/boost-binaries/1.64.0/boost_1_64_0-msvc-14.1-64.exe/download). Just ignore me if higher boost versions affect Linux compilation. Thanks for your respond.

**Comment by lochel** [comment]
I see; VS 2017 is actually msvc-14.1. However, upgrading boost is unfortunately not an option.

**Comment by adrpo** [comment]
Can you support different boost versions via some ifdefs?

**Comment by lochel** [comment]
The cmake files require boost 1.54 as a minimum. So it should work with different boost versions. However, we had issues with different simulation output for different boost versions in the past, but that could be fixed in the meantime.

**Comment by sjoelund** [comment]
@lochel The issue was that you thought an older Boost produced different results, right? But actually it was because a non-ordered set was used somewhere and it was just luck that made simulations succeed. I don't think we had much problem due to different boost versions being used for this project. The problem with requiring newer Boost versions is that they are not available in Ubuntu  (2014 LTS is still supported and only has Boost 1.54; 17.10 has Boost 1.62 and 18.04 LTS will have Boost 1.65), but of course Windows doesn't come with either of them so you can just recommend in the instructions that you install Boost 1.64+ for the VS2017 binaries.

**Comment by lochel** [comment]
I tried now to compile everything with VS2017 and Boost 1.64, but for some reason cmake cannot find the Boost libs.

**Comment by lochel** [comment]
Apparently, boost 1.64 requires cmake 3.8 or newer.

**Comment by sjoelund** [comment]
You shouldn't require cmake 3.8; the project builds just fine with lower versions (cmake 2.8 is in Ubuntu 14.04 LTS; cmake 3.5 in 16.04 LTS). Most systems with a lower version of cmake will have a lower version of boost anyway (or just have the higher cmake_require for Windows?)

**Pull request merged**
