### PR TITLE
Implement oms3_setLoggingLevel

### PR DESCRIPTION
**Pull request by lochel**
### Related Issues

#528

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/920//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#534

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :raised_hands:

**Comment by robbr48** [comment]
This should also be propagated to OMTLMSimulator.

**Comment by lochel** [comment]
What does it mean? Is TLM simulator using a different logging system?

**Comment by robbr48** [comment]
Yes, it writes to TLMlogfile.log. 

For oms2 we had a special `oms2_setTLMLoggingLevel` API function, but perhaps we can translate the OMSimulator log level to the `TLMLogLevel` used in OMTLMSimulator.

Available log levels are: Disabled, Fatal, Warning, Info, Debug

**Comment by lochel** [comment]
I think we should use the OMSimulator logging system for the TLM simulator. Maybe we can register a callback function to handle the logging, similar to the FMIL. That way SKF would not depend on it.

**Pull request closed without merging**
