### PR TITLE
Extrapolation of inputs

### PR DESCRIPTION
**Pull request by lochel**
### Related Issues

#157 

### Purpose

Fix oscillations in FMI co-simulation

### Approach

Utilize output derivatives to extraploate connected inputs.

### Type of Change

- New feature (non-breaking change which adds functionality)

### Checklist

- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- My changes generate no new warnings

### CODE REVIEW

**Comment by lochel** [comment]
@adeas31, you can display `maxOutputDerivativeOrder` in OMEdit once this is merged.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/925//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#540

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :bowtie:

**Comment by meek1** [comment]
@lochel, how did you solve the plotting of inputs? I guess sawtooth extrapolation look of the signal should not be shown, or?

**Comment by meek1** [comment]
OK, is ”continuous input extrapolation” the same thing as ”smoothing” in #204?

Please see also question on number of FMU internal steps in #204.

**Comment by lochel** [comment]
> OK, is ”continuous input extrapolation” the same thing as ”smoothing” in #204?

Exactly, smoothing using directional derivatives

> Please see also question on number of FMU internal steps in #204.

I don't think that this information can be exposed.

**Pull request closed without merging**
