### PR TITLE
Support static linking again

### PR DESCRIPTION
**Pull request by sjoelund**
- Added OMTLM=OFF to be able to disable TLM (since it is no longer linked
  statically).
- Stopped generating .so-files in the bin-directory (only used on Windows)

### Related Issues

#249 

### Purpose

Allow ARM clients to build static executable so we can simulate FMUs on weird embedded platforms

### Approach

Adds an option to compile without OMTLMSimulator (this is a partial fix; better would be to be able to optionally statically link the TLM libraries).

### Type of Change

- Bug fix
- New feature

### Checklist

- I have performed a self-review of my own code

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/428//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#250

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/428//console)** The job failed to compile. :disappointed:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/429//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#250

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/429//console)** The job failed to compile. :worried:

**Comment by lochel** [comment]
Hopefully there is a better way of doing this… The code actually looks very painful.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/430//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#250

The changes will be pushed if all tests run successfully.

**Comment by sjoelund** [comment]
Yes, the code does look ugly (the usual case with ifdef). But the actual error-messages become better with it and makes OMSimulator a bit more usable with the flag set.

**Comment by OpenModelica-Hudson** [comment]
**[Mac:](https://test.openmodelica.org/hudson/job/OMSimulator-PR-MacOSX/277//console)** The job failed to compile. :-1:

**Comment by OpenModelica-Hudson** [comment]
**[Windows-GCC:](https://test.openmodelica.org/hudson/job/OMSimulator-PR-Windows/290//console)** The job failed to compile. :worried:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/431//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#250

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Windows-GCC:](https://test.openmodelica.org/hudson/job/OMSimulator-PR-Windows/291//console)** The job failed to compile. :cry:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/433//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#250

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :bowtie:

**Pull request closed without merging**
