### PR TITLE
Fix arm build

### PR DESCRIPTION
**Pull request by lochel**
### Related Issues

https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OMSimulator/detail/master/16/changes 

### Purpose

Fix arm build.

### Type of Change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/609//console)** The job failed to compile. :disappointed:

**Comment by sjoelund** [comment]
You could wait with starting the PR job until the Jenkins CI hook gives you a success :)

**Comment by lochel** [comment]
The Hudson job reports the issues faster :wink:

**Comment by lochel** [comment]
Now the Jenkins CI couldn't update the submodules. Why is that?

**Comment by sjoelund** [comment]
The antivirus on the Windows machine

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :+1:

**Pull request closed without merging**
