### PR TITLE
[Jenkins] Compile CentOS 6

### PR DESCRIPTION
**Pull request by sjoelund**
### Purpose

Test building on CentOS 6 (not expected to work yet)

### CODE REVIEW

**Comment by sjoelund** [comment]
@lochel I look for boost/lockfree to disable CTPL if it doesn't exist now. But there are other things that are not in the older Boost versions in EL6 (you can fix things in this PR and see how the centos-6 job behaves):
```
/var/lib/jenkins/workspace/OMSimulator_PR-333-UG5YL6CXOLPBHWBKPUJHA2SH7MIWU4XHUCIW2ZKHPNWZMDTAF5XA/src/OMSimulatorLib/Scope.cpp:52:57: error: 'temp_directory_path' is not a member of 'boost::filesystem'

   boost::filesystem::path tempPath = boost::filesystem::temp_directory_path();
```

**Comment by sjoelund** [comment]
Note that CentOS6 actually has support for:
```
#include <iostream>
#if __has_include(<filesystem>)
  // TODO
#elif __has_include(<experimental/filesystem>)
#include <experimental/filesystem>
namespace fs = std::experimental::filesystem::v1;
#else
#include <boost/filesystem.hpp>
namespace fs = boost::filesystem;
#endif
int main()
{
    std::cout << "Temp directory is " << fs::temp_directory_path() << '\n';
}
```
It requires linking with `-lstdc++fs` which is a static library.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/600//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#333

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Windows-GCC:](https://test.openmodelica.org/hudson//job/OMSimulator-PR-Windows/413)** The test suite is unstable. :unamused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/601//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#333

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :blush:

**Pull request closed without merging**
