### PR TITLE
Only update the connection geometry

### PR DESCRIPTION
**Pull request by lochel**
### Related Issues

Reported by @adeas31 

### Purpose

Only update the connection geometry

### Type of Change

- Bug fix (non-breaking change which fixes an issue)

### Checklist

- I have performed a self-review of my own code

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/816//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#472

The changes will be pushed if all tests run successfully.

**Comment by lochel** [comment]
@adeas31 I guess you have to push the OMEdit changes right after this is merged, because otherwise the OpenModelica build will be broken.

**Comment by adeas31** [comment]
I already have a PR ready :)
https://github.com/OpenModelica/OMEdit/pull/193

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/819//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#472

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/819//console)** Wrong hash: got db4fc3fad4693e3c1fb0805299928619e2f5638f; expected 157b056ca1ec573d5eeac37177ae60fff38a01fc

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/820//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#472

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Windows-MSVC:](https://test.openmodelica.org/hudson/job/OMSimulator-PR-Windows/563//console)** The job failed to compile. :unamused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/821//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#472

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[ASan:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/821/)** The test suite is unstable. :unamused:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/822//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#472

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :confetti_ball:

**Pull request closed without merging**
