### PR TITLE
Fix version to alpine:3.12

### PR DESCRIPTION
**Pull request by sjoelund**
Reverts #912

### CODE REVIEW

**Comment by sjoelund** [comment]
You might want to fix this:

```
Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7f0a27ebb458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
    #1 0x561d75733e00 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<oms::System* const, std::mutex> > >::allocate(unsigned long, void const*) /usr/include/c++/7/ext/new_allocator.h:111
    #2 0x561d757329e7 in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<oms::System* const, std::mutex> > > >::allocate(std::allocator<std::_Rb_tree_node<std::pair<oms::System* const, std::mutex> > >&, unsigned long) /usr/include/c++/7/bits/alloc_traits.h:436
    #3 0x561d7572e6fc in std::_Rb_tree<oms::System*, std::pair<oms::System* const, std::mutex>, std::_Select1st<std::pair<oms::System* const, std::mutex> >, std::less<oms::System*>, std::allocator<std::pair<oms::System* const, std::mutex> > >::_M_get_node() (/var/lib/jenkins1/ws/OMSimulator_PR-914/install/linux/bin/OMSimulator+0x4666fc)
    #4 0x561d7572808e in std::_Rb_tree_node<std::pair<oms::System* const, std::mutex> >* std::_Rb_tree<oms::System*, std::pair<oms::System* const, std::mutex>, std::_Select1st<std::pair<oms::System* const, std::mutex> >, std::less<oms::System*>, std::allocator<std::pair<oms::System* const, std::mutex> > >::_M_create_node<std::piecewise_construct_t const&, std::tuple<oms::System*&&>, std::tuple<> >(std::piecewise_construct_t const&, std::tuple<oms::System*&&>&&, std::tuple<>&&) (/var/lib/jenkins1/ws/OMSimulator_PR-914/install/linux/bin/OMSimulator+0x46008e)
    #5 0x561d7572295d in std::_Rb_tree_iterator<std::pair<oms::System* const, std::mutex> > std::_Rb_tree<oms::System*, std::pair<oms::System* const, std::mutex>, std::_Select1st<std::pair<oms::System* const, std::mutex> >, std::less<oms::System*>, std::allocator<std::pair<oms::System* const, std::mutex> > >::_M_emplace_hint_unique<std::piecewise_construct_t const&, std::tuple<oms::System*&&>, std::tuple<> >(std::_Rb_tree_const_iterator<std::pair<oms::System* const, std::mutex> >, std::piecewise_construct_t const&, std::tuple<oms::System*&&>&&, std::tuple<>&&) /usr/include/c++/7/bits/stl_tree.h:2398
    #6 0x561d7571de31 in std::map<oms::System*, std::mutex, std::less<oms::System*>, std::allocator<std::pair<oms::System* const, std::mutex> > >::operator[](oms::System*&&) (/var/lib/jenkins1/ws/OMSimulator_PR-914/install/linux/bin/OMSimulator+0x455e31)
    #7 0x561d7570d507 in oms::SystemTLM::readFromSockets(oms::SystemWC*, double, oms::Component*) /var/lib/jenkins2/ws/OMSimulator_PR-914/src/OMSimulatorLib/TLM/SystemTLM.cpp:688
    #8 0x561d757833b1 in oms::ComponentFMUCS::stepUntil(double) /var/lib/jenkins2/ws/OMSimulator_PR-914/src/OMSimulatorLib/ComponentFMUCS.cpp:633
    #9 0x561d756a44bf in oms::SystemWC::stepUntil(double, void (*)(char const*, double, oms_status_enu_t)) /var/lib/jenkins2/ws/OMSimulator_PR-914/src/OMSimulatorLib/SystemWC.cpp:603
    #10 0x561d75709b40 in oms::SystemTLM::simulateSubSystem(oms::ComRef, double) /var/lib/jenkins2/ws/OMSimulator_PR-914/src/OMSimulatorLib/TLM/SystemTLM.cpp:587
    #11 0x561d75720c1f in oms_status_enu_t std::__invoke_impl<oms_status_enu_t, oms_status_enu_t (oms::SystemTLM::*)(oms::ComRef, double), oms::SystemTLM*, oms::ComRef, double>(std::__invoke_memfun_deref, oms_status_enu_t (oms::SystemTLM::*&&)(oms::ComRef, double), oms::SystemTLM*&&, oms::ComRef&&, double&&) /usr/include/c++/7/bits/invoke.h:73
    #12 0x561d7571c65e in std::__invoke_result<oms_status_enu_t (oms::SystemTLM::*)(oms::ComRef, double), oms::SystemTLM*, oms::ComRef, double>::type std::__invoke<oms_status_enu_t (oms::SystemTLM::*)(oms::ComRef, double), oms::SystemTLM*, oms::ComRef, double>(oms_status_enu_t (oms::SystemTLM::*&&)(oms::ComRef, double), oms::SystemTLM*&&, oms::ComRef&&, double&&) /usr/include/c++/7/bits/invoke.h:96
    #13 0x561d7573608a in decltype (__invoke((_S_declval<0ul>)(), (_S_declval<1ul>)(), (_S_declval<2ul>)(), (_S_declval<3ul>)())) std::thread::_Invoker<std::tuple<oms_status_enu_t (oms::SystemTLM::*)(oms::ComRef, double), oms::SystemTLM*, oms::ComRef, double> >::_M_invoke<0ul, 1ul, 2ul, 3ul>(std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) /usr/include/c++/7/thread:234
    #14 0x561d75735f56 in std::thread::_Invoker<std::tuple<oms_status_enu_t (oms::SystemTLM::*)(oms::ComRef, double), oms::SystemTLM*, oms::ComRef, double> >::operator()() /usr/include/c++/7/thread:243
    #15 0x561d75735ed1 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<oms_status_enu_t (oms::SystemTLM::*)(oms::ComRef, double), oms::SystemTLM*, oms::ComRef, double> > >::_M_run() /usr/include/c++/7/thread:186
    #16 0x561d7597dcee in execute_native_thread_routine (/var/lib/jenkins1/ws/OMSimulator_PR-914/install/linux/bin/OMSimulator+0x6b5cee)
 ```

**Comment by lochel** [comment]
> You might want to fix this:
> 
> ```
> Direct leak of 80 byte(s) in 1 object(s) allocated from:
>     #0 0x7f0a27ebb458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
>     #1 0x561d75733e00 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<oms::System* const, std::mutex> > >::allocate(unsigned long, void const*) /usr/include/c++/7/ext/new_allocator.h:111
>     #2 0x561d757329e7 in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<oms::System* const, std::mutex> > > >::allocate(std::allocator<std::_Rb_tree_node<std::pair<oms::System* const, std::mutex> > >&, unsigned long) /usr/include/c++/7/bits/alloc_traits.h:436
>     #3 0x561d7572e6fc in std::_Rb_tree<oms::System*, std::pair<oms::System* const, std::mutex>, std::_Select1st<std::pair<oms::System* const, std::mutex> >, std::less<oms::System*>, std::allocator<std::pair<oms::System* const, std::mutex> > >::_M_get_node() (/var/lib/jenkins1/ws/OMSimulator_PR-914/install/linux/bin/OMSimulator+0x4666fc)
>     #4 0x561d7572808e in std::_Rb_tree_node<std::pair<oms::System* const, std::mutex> >* std::_Rb_tree<oms::System*, std::pair<oms::System* const, std::mutex>, std::_Select1st<std::pair<oms::System* const, std::mutex> >, std::less<oms::System*>, std::allocator<std::pair<oms::System* const, std::mutex> > >::_M_create_node<std::piecewise_construct_t const&, std::tuple<oms::System*&&>, std::tuple<> >(std::piecewise_construct_t const&, std::tuple<oms::System*&&>&&, std::tuple<>&&) (/var/lib/jenkins1/ws/OMSimulator_PR-914/install/linux/bin/OMSimulator+0x46008e)
>     #5 0x561d7572295d in std::_Rb_tree_iterator<std::pair<oms::System* const, std::mutex> > std::_Rb_tree<oms::System*, std::pair<oms::System* const, std::mutex>, std::_Select1st<std::pair<oms::System* const, std::mutex> >, std::less<oms::System*>, std::allocator<std::pair<oms::System* const, std::mutex> > >::_M_emplace_hint_unique<std::piecewise_construct_t const&, std::tuple<oms::System*&&>, std::tuple<> >(std::_Rb_tree_const_iterator<std::pair<oms::System* const, std::mutex> >, std::piecewise_construct_t const&, std::tuple<oms::System*&&>&&, std::tuple<>&&) /usr/include/c++/7/bits/stl_tree.h:2398
>     #6 0x561d7571de31 in std::map<oms::System*, std::mutex, std::less<oms::System*>, std::allocator<std::pair<oms::System* const, std::mutex> > >::operator[](oms::System*&&) (/var/lib/jenkins1/ws/OMSimulator_PR-914/install/linux/bin/OMSimulator+0x455e31)
>     #7 0x561d7570d507 in oms::SystemTLM::readFromSockets(oms::SystemWC*, double, oms::Component*) /var/lib/jenkins2/ws/OMSimulator_PR-914/src/OMSimulatorLib/TLM/SystemTLM.cpp:688
>     #8 0x561d757833b1 in oms::ComponentFMUCS::stepUntil(double) /var/lib/jenkins2/ws/OMSimulator_PR-914/src/OMSimulatorLib/ComponentFMUCS.cpp:633
>     #9 0x561d756a44bf in oms::SystemWC::stepUntil(double, void (*)(char const*, double, oms_status_enu_t)) /var/lib/jenkins2/ws/OMSimulator_PR-914/src/OMSimulatorLib/SystemWC.cpp:603
>     #10 0x561d75709b40 in oms::SystemTLM::simulateSubSystem(oms::ComRef, double) /var/lib/jenkins2/ws/OMSimulator_PR-914/src/OMSimulatorLib/TLM/SystemTLM.cpp:587
>     #11 0x561d75720c1f in oms_status_enu_t std::__invoke_impl<oms_status_enu_t, oms_status_enu_t (oms::SystemTLM::*)(oms::ComRef, double), oms::SystemTLM*, oms::ComRef, double>(std::__invoke_memfun_deref, oms_status_enu_t (oms::SystemTLM::*&&)(oms::ComRef, double), oms::SystemTLM*&&, oms::ComRef&&, double&&) /usr/include/c++/7/bits/invoke.h:73
>     #12 0x561d7571c65e in std::__invoke_result<oms_status_enu_t (oms::SystemTLM::*)(oms::ComRef, double), oms::SystemTLM*, oms::ComRef, double>::type std::__invoke<oms_status_enu_t (oms::SystemTLM::*)(oms::ComRef, double), oms::SystemTLM*, oms::ComRef, double>(oms_status_enu_t (oms::SystemTLM::*&&)(oms::ComRef, double), oms::SystemTLM*&&, oms::ComRef&&, double&&) /usr/include/c++/7/bits/invoke.h:96
>     #13 0x561d7573608a in decltype (__invoke((_S_declval<0ul>)(), (_S_declval<1ul>)(), (_S_declval<2ul>)(), (_S_declval<3ul>)())) std::thread::_Invoker<std::tuple<oms_status_enu_t (oms::SystemTLM::*)(oms::ComRef, double), oms::SystemTLM*, oms::ComRef, double> >::_M_invoke<0ul, 1ul, 2ul, 3ul>(std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) /usr/include/c++/7/thread:234
>     #14 0x561d75735f56 in std::thread::_Invoker<std::tuple<oms_status_enu_t (oms::SystemTLM::*)(oms::ComRef, double), oms::SystemTLM*, oms::ComRef, double> >::operator()() /usr/include/c++/7/thread:243
>     #15 0x561d75735ed1 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<oms_status_enu_t (oms::SystemTLM::*)(oms::ComRef, double), oms::SystemTLM*, oms::ComRef, double> > >::_M_run() /usr/include/c++/7/thread:186
>     #16 0x561d7597dcee in execute_native_thread_routine (/var/lib/jenkins1/ws/OMSimulator_PR-914/install/linux/bin/OMSimulator+0x6b5cee)
> ```

Sure, but we don't know how. @robbr48 and me tried to find the problem for some time and gave up on it.

**Comment by sjoelund** [comment]
> Sure, but we don't know how. @robbr48 and me tried to find the problem for some time and gave up on it.

Kill that thread before exiting the process?

**Comment by lochel** [comment]
Please make a PR if you know how to fix it 😃 👍

**Pull request merged**
