### PR TITLE
Update the CLI to use oms3

### PR DESCRIPTION
**Pull request by lochel**
### Purpose

Update the CLI to use oms3

### Type of Change

- Code refactoring (non-breaking change which improves maintainability)
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

### Checklist

- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/861//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#491

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[ASan:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/861/)** The test suite is unstable. :disappointed:

**Comment by lochel** [comment]
@robbr48 ASAN failed again due to the TLM implementation. It almost complains for each of my PRs. That is not really fun ...

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/862//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#491

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Windows-MSVC:](https://test.openmodelica.org/hudson/job/OMSimulator-PR-Windows/591//console)** The job failed to compile. :worried:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/863//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#491

The changes will be pushed if all tests run successfully.

**Comment by robbr48** [comment]
I fixed the threading issues, which have caused almost all the recent failures. This one is related to socket connection, and likely caused by two models trying to connect to the same port. This is difficult to protect against when the test models are executed in parallel. The code is written for only running one TLM manager at a time. I could try to increase the difference in desired ports for the tests, but it would never guarantee stability completely.


12 nov. 2018 kl. 21:51 skrev Lennart Ochel <notifications@github.com<mailto:notifications@github.com>>:


@robbr48<https://github.com/robbr48> ASAN failed again due to the TLM implementation. It almost complains for each of my PRs. That is not really fun ...

**Comment by lochel** [comment]
@robbr48 I can think of two possible solutions: Define fixed and different ports for all TLM tests (disable the port scanning heuristic) or combine all TLM tests into a single test file and run the different scenarios sequentially.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/864//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#491

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/866//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#491

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/868//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#491

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :blush:

**Comment by robbr48** [comment]
@lochel Fixed ports would not solve the problem. Then the test model would fail if the requested port is not available. If all ports were available, it would work with the current solution. Collisions occur because models need to increment port numbers when a port is not available.

**Pull request closed without merging**
