### PR TITLE
Implement oms3_simulate_asynchronous

### PR DESCRIPTION
**Pull request by lochel**
### Purpose

Implement `oms3_simulate_asynchronous`, which is required for the GUI.

### Type of Change

- New feature (non-breaking change which adds functionality)

### Checklist

- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by adeas31** [comment]
I will test it ASAP.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/817//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#454

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/823//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#454

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :smiley:

**Pull request closed without merging**
