### PR TITLE
Add global flags, e.g. to supress path information

### PR DESCRIPTION
**Pull request by lochel**
### Purpose

In order to run the tests on different systems, the path information need to be supressed from the log messages.

### Approach

Add a new function `oms3_setCommandLineOption(<string>)` to set global flags.

### Type of Change

- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by lochel** [comment]
`oms3_setCommandLineOption("--suppressPath=true")` can be used to supress path information in the testsuite.

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/617//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#360
  - OpenModelica/OMSimulator-testsuite#78

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/617/)** The test suite is unstable. :-1:

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/618//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#360
  - OpenModelica/OMSimulator-testsuite#78

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :sun_with_face:

**Pull request closed without merging**
