### PR TITLE
Export and import  element geometry to/from SSD

### PR DESCRIPTION
**Pull request by lochel**
### Related Issues

Reported by @adeas31 

### Purpose

Export and import  element geometry to/from SSD

### Type of Change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by lochel** [comment]
@adeas31 I fixed also the delete function for system connectors, so that all associated connections get automatically removed.

**Comment by adeas31** [comment]
I think we should not do that. OMEdit will not be able to add the connections back in the undo case then. If OMEdit deletes the connections then it can add them back on undo.

**Comment by lochel** [comment]
Well, we do it also for systems and components.

**Comment by lochel** [comment]
How do you undo the deletion of a system?

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/828//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#475

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :+1:

**Pull request closed without merging**
