### PR TITLE
copy all dlls to OMSimulator package

### PR DESCRIPTION
**Pull request by arun3688**
### Purpose

 This PR  copies all the dlls to OMSimulator root package to be consistent with all platforms especially for `mingw `and `windows` where the dlls are stored in `bin` directory

### CODE REVIEW

**Comment by lochel** [comment]
@adrpo I guess these changes require to adapt the OpenModelica installers, right?

**Comment by adrpo** [comment]
Yes, I can copy the entire build/lib/OMSimulator and then it should be fine. Just let me know when this is merged and I'll fix it quickly.

**Comment by arun3688** [comment]
@lochel i guess this can be pushed now

**Comment by adrpo** [comment]
I adapted the Windows installer: https://github.com/OpenModelica/OpenModelicaSetup/commit/13d7fdb5fa0c65883ebacc875ea42070c49264ca

**Review by lochel — APPROVED** [review]

**Pull request merged**
