### PR TITLE
New API to set special flags, e.g. for workarounds

### PR DESCRIPTION
**Pull request by lochel**
### Related Issues

https://github.com/OpenModelica/OMSimulator/issues/169#issuecomment-397446497

### Purpose

Add special flag to fetch all variables of a given FMU.

### Approach

New API `oms2_setFlags(const char* cref, const char* flags);`.

### Type of Change

- Code refactoring (non-breaking change which improves maintainability)
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

### Checklist

- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- My changes generate no new warnings

### CODE REVIEW

**Comment by lochel** [comment]
The documentation cannot be updated before #224 is merged...

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/438//console). It may take a while, depending on the workload.
  - OpenModelica/OMSimulator#252

The changes will be pushed if all tests run successfully.

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :+1:

**Comment by meek1** [comment]
I guess the flag fetchAllVars is disabled by default, i.e. -fetchAllVars?

**Comment by lochel** [comment]
Yes, it is disabled by default.

**Pull request closed without merging**
